version: '3.3'
services:
  # Add postgres container
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2a101DcMv/hyMIooiqHRXdmtD.
      POSTGRES_USER: "mariomix"
      POSTGRES_DB: tasks-manager

  #Task API container
  task-api:
    image: task-api:latest
    links:
      - db
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_USER: mariomix
      DB_PASS: 2a101DcMv/hyMIooiqHRXdmtD.
      ACCESS_TOKEN_SECRET: 2a10uMh.EOsPdIbuGXLeVp5F6e
      REFRESH_TOKEN_SECRET: 5a8pQ0ly84k5QwkyGgFquLqpJ6tI5bm5mNoqShTx9du
    depends_on:
      - db
    restart: always
    # Create volumes so I can develop using the container
    volumes:
      - /taskAPI/node_modules
      - ./server:/taskAPI